#
#
#

# Parameters for the Q-Learning function
y: 0.95
eps: 0.2
decay_factor: 0.999

# Every how many episodes display the update in q-learning?
num_episodes_update: 100

# Num. of episodes to run simulate and learn
num_episodes: 1000

# States
states:
  value:
    names:
      - 'EVEN'
      - 'WIN'
      - 'LOSE'
  forecast:
    names:
      - 'EVEN'
      - 'WIN'
      - 'LOSE'
  shares:
    names:
      - 'HAVE'
      - 'DONTHAVE'