#
# Predictor Parameters
#

# delimiter used in the CSV file for the OHLC+V information.
# and dictionary to understand CSV columns
delimiter: ','
csv_dict:
  d: 'Date'
  o: 'Open'
  h: 'High'
  l: 'Low'
  c: 'Close'
cse_tags: ['b', 'o', 'h', 'l', 'c']

# Saving predictions. The first one is only the path to be used when saving
# predict_training. The second one (json_predict_path) is the name of the
# json file used during the pipeline execution (highly ephemeral)
predictions_path: ../output
json_prediction: ../output/tmp_prediction.json
json_forecast: ../output/tmp_forecast.json

# Format of the screen output for predict_training. These are values to be
# accepted by 'tabulate'.
table_format: simple

# Files, Networks, Names...
models_dir: ../staging
subtypes: ['body', 'move']
model_names:
  8yw20:
    body: body_acciona_2010_2018_w20_e100
    move: move_acciona_2010_2018_w20_e100
    encoder: encoder_acciona_2010_2018_w20
  8yw10:
    body: body_acciona_2010_2018_w10_e100
    move: move_acciona_2010_2018_w10_e100
    encoder: encoder_acciona_2010_2018_w10
  8yw05:
    body: body_acciona_2010_2018_w5_e100
    move: move_acciona_2010_2018_w5_e100
    encoder: encoder_acciona_2010_2018_w5
#
# DAX
#
#  4yw30:
#    body: body_DAX_2015_2019_w30_e100
#    move: move_DAX_2015_2019_w30_e100
#    encoder: encoder_DAX_2015_2019_w30
#  4yw20:
#    body: body_DAX_2015_2019_w20_e100
#    move: move_DAX_2015_2019_w20_e100
#    encoder: encoder_DAX_2015_2019_w20
#  4yw10:
#    body: body_DAX_2015_2019_w10_e100
#    move: move_DAX_2015_2019_w10_e100
#    encoder: encoder_DAX_2015_2019_w10

# Seed to be used to initialize the whole system.
seed: 1

# training parameters
loss: mean_squared_error
optimizer: adam
metrics: ['accuracy']
batch_size: 10
window_size: 1
validation_split: 0.1
test_size: 0.1
verbose: 3
num_predictions: 1

# model parameters
l1units: 128
l2units: 128
activation: tanh
dropout: 0.1
