#
# Predictor Parameters
#

# data dependencies
ticks_file: ../data/acciona_2010_2018.csv
delimiter: ','

# Dictionary to understand CSV columns
csv_dict:
  o: 'Open'
  h: 'High'
  l: 'Low'
  c: 'Close'

cse_tags: ['b', 'o', 'h', 'l', 'c']

# Saving predictions
save_predictions: true
predictions_path: ../output

# When in "predict", do I run "n" random predictions or do I run predictions
# over an entire dataset
predict_training: true
table_format: simple

# Files, Networks, Names...
models_dir: ../output
subtypes: ['body', 'move']
model_names:
  8yw20:
    body: body_acciona_2010_2018_w20_e100
    move: move_acciona_2010_2018_w20_e100
    encoder: encoder_acciona_2010_2018_w20
  8yw10:
    body: body_acciona_2010_2018_w10_e100
    move: move_acciona_2010_2018_w10_e100
    encoder: encoder_acciona_2010_2018_w10
  8yw05:
    body: body_acciona_2010_2018_w10_e100
    move: move_acciona_2010_2018_w10_e100
    encoder: encoder_acciona_2010_2018_w10

# Log level: 0: Silent, 1: Errors only, 2: Warnings too, 3: info, 4: debug
log_level: 3

# Do I want the plots with the history of training?
plot: false

# training parameters
loss: mean_squared_error
optimizer: adam
metrics: ['accuracy']
epochs: 100
batch_size: 10
window_size: 1
validation_split: 0.1
test_size: 0.1
verbose: 3
num_predictions: 1

# model parameters
l1units: 128
l2units: 128
activation: tanh
dropout: 0.1

# Do I use the ensemble part?
ensemble_path: ../output/ridge_l2_model.pkl
