#
# Parameters for the indicators calculator.
#

# Log level
log_level: 3

# Input data
input_data: ../data/acciona_2010_2018.csv
separator: ','

# Fuse dataframes
forecast_file: ../output/forecast_acciona_2010_2018.csv

# Names of the relevant columns in the data file
csv_dict:
  date: Date
  open: Open
  high: High
  low: Low
  close: Close
  volume: Volume

output_path: ../output

# Names of columns containing the index information
indicator_dict:
  konkorde:
    - verde
    - azul