#
#
#

# Parameters for the Q-Learning function
y: 0.95
eps: 0.2
decay_factor: 0.999

# Every how many episodes display the update in q-learning?
num_episodes_update: 100

# Num. of episodes to run simulate and learn
num_episodes: 100

# Different states in which the environment might be.
state:
  portfolio_value:
    names:
      - EVEN
      - WIN
      - LOSE
  forecast:
    names:
      - EVEN
      - WIN
      - LOSE
  got_shares:
    names:
      - HAVE
      - DONTHAVE

# Actions to be accomplished by the agent.
action:
  - do_nothing
  - buy
  - sell

# environment variables
environment:
  initial_budget: 1000.
